[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
	"python -m venv /app/.venv",
	"/app/.venv/bin/pip install --upgrade pip setuptools wheel",
	"/app/.venv/bin/pip install -r Backend/requirements.txt"
]

[start]
cmd = "/app/.venv/bin/uvicorn Backend.api.main:app --host 0.0.0.0 --port $PORT"
