import type { QuoteResult, StatsOverview, RegionalStats } from "./types";

export const MOCK_QUOTES: QuoteResult[] = [
  {
    quote_num: "Q-20250305-0001",
    agent_type: "EA",
    region: "Northeast",
    timestamp: "2025-03-05T09:15:22Z",
    re_quote: false,
    quoted_premium: 1245.0,
    coverage: "Enhanced",
    sal_range: "50K-75K",
    vehicl_cost_range: "25K-35K",
    driver_age: 34,
    driving_exp: 12,
    prev_accidents: 0,
    prev_citations: 1,
    risk_tier: "LOW",
    risk_score: 0.18,
    risk_shap: [
      { feature: "Prev_Accidents", value: 0, impact: -0.32 },
      { feature: "Driving_Exp", value: 12, impact: -0.21 },
      { feature: "Driver_Age", value: 34, impact: -0.15 },
    ],
    risk_lime: { Prev_Accidents: -0.28, Driving_Exp: -0.19, Prev_Citations: 0.08 },
    risk_anchors: "IF Prev_Accidents = 0 AND Driving_Exp >= 8 THEN LOW risk (precision: 94%)",
    risk_counterfactuals: [
      {
        original: { Prev_Accidents: 0, Driving_Exp: 12 },
        changed: { Prev_Accidents: 2, Driving_Exp: 12 },
        outcome: "HIGH risk",
      },
    ],
    bind_score: 82,
    bind_probability: 0.82,
    bind_shap: [
      { feature: "Quoted_Premium", value: 1245, impact: 0.15 },
      { feature: "Coverage", value: 2, impact: 0.11 },
      { feature: "Agent_Type", value: 1, impact: 0.08 },
    ],
    bind_lime: { Quoted_Premium: 0.12, Coverage: 0.09, Sal_Range: 0.07 },
    bind_anchors: "IF risk_tier = LOW AND Quoted_Premium < 1500 AND Agent_Type = EA THEN bind (precision: 88%)",
    bind_counterfactuals: [
      {
        original: { Quoted_Premium: 1245, Coverage: "Enhanced" },
        changed: { Quoted_Premium: 1800, Coverage: "Enhanced" },
        outcome: "No bind",
      },
    ],
    urgency_days: 12,
    premium_flag: "ACCEPTABLE",
    adjusted_band: "$1100-$1350",
    premium_reasoning: "Premium of $1,245 falls within the expected range for Enhanced coverage in the Northeast region. The salary-to-premium ratio is sustainable at the 50K-75K income bracket.",
    decision: "AUTO_APPROVE",
    case_summary: "Low-risk profile with strong conversion signals. Premium is competitively positioned. Recommended for automatic approval.",
    confidence: 0.91,
  },
  {
    quote_num: "Q-20250305-0002",
    agent_type: "IA",
    region: "Southeast",
    timestamp: "2025-03-05T09:18:45Z",
    re_quote: true,
    quoted_premium: 2180.0,
    coverage: "Enhanced",
    sal_range: "35K-50K",
    vehicl_cost_range: "35K-50K",
    driver_age: 22,
    driving_exp: 3,
    prev_accidents: 2,
    prev_citations: 3,
    risk_tier: "HIGH",
    risk_score: 0.87,
    risk_shap: [
      { feature: "Prev_Accidents", value: 2, impact: 0.41 },
      { feature: "Driver_Age", value: 22, impact: 0.28 },
      { feature: "Prev_Citations", value: 3, impact: 0.22 },
    ],
    risk_lime: { Prev_Accidents: 0.38, Driver_Age: 0.25, Driving_Exp: 0.18 },
    risk_anchors: "IF Prev_Accidents >= 2 AND Driver_Age < 25 THEN HIGH risk (precision: 96%)",
    risk_counterfactuals: [
      {
        original: { Prev_Accidents: 2, Driver_Age: 22 },
        changed: { Prev_Accidents: 0, Driver_Age: 22 },
        outcome: "MEDIUM risk",
      },
    ],
    bind_score: 74,
    bind_probability: 0.74,
    bind_shap: [
      { feature: "Re_Quote", value: 1, impact: 0.18 },
      { feature: "Quoted_Premium", value: 2180, impact: -0.14 },
      { feature: "risk_tier", value: 2, impact: -0.12 },
    ],
    bind_lime: { Re_Quote: 0.16, Quoted_Premium: -0.11, risk_tier: -0.1 },
    bind_anchors: "IF Re_Quote = Yes AND risk_tier = HIGH THEN uncertain (precision: 62%)",
    bind_counterfactuals: [
      {
        original: { Quoted_Premium: 2180, Coverage: "Enhanced" },
        changed: { Quoted_Premium: 1600, Coverage: "Balanced" },
        outcome: "Bind likely",
      },
    ],
    urgency_days: 3,
    premium_flag: "BLOCKER",
    adjusted_band: "$1500-$1800",
    premium_reasoning: "Premium of $2,180 exceeds the affordability threshold for the 35K-50K salary bracket by approximately 21%. The re-quote status suggests price sensitivity. Recommend reducing to the $1,500-$1,800 band with Balanced coverage.",
    decision: "ESCALATE_UNDERWRITER",
    case_summary: "High-risk young driver with accident history. Re-quote indicates price sensitivity. Premium is disproportionate to salary range. Requires underwriter assessment for potential manual rate adjustment.",
    confidence: 0.58,
  },
  {
    quote_num: "Q-20250305-0003",
    agent_type: "EA",
    region: "Midwest",
    timestamp: "2025-03-05T09:22:10Z",
    re_quote: false,
    quoted_premium: 890.0,
    coverage: "Basic",
    sal_range: "35K-50K",
    vehicl_cost_range: "15K-25K",
    driver_age: 45,
    driving_exp: 25,
    prev_accidents: 1,
    prev_citations: 0,
    risk_tier: "MEDIUM",
    risk_score: 0.42,
    risk_shap: [
      { feature: "Prev_Accidents", value: 1, impact: 0.18 },
      { feature: "Driving_Exp", value: 25, impact: -0.25 },
      { feature: "Driver_Age", value: 45, impact: -0.12 },
    ],
    risk_lime: { Prev_Accidents: 0.15, Driving_Exp: -0.22, Driver_Age: -0.1 },
    risk_anchors: "IF 0 < Prev_Accidents < 2 AND Driving_Exp >= 15 THEN MEDIUM risk (precision: 82%)",
    risk_counterfactuals: [
      {
        original: { Prev_Accidents: 1, Driving_Exp: 25 },
        changed: { Prev_Accidents: 0, Driving_Exp: 25 },
        outcome: "LOW risk",
      },
    ],
    bind_score: 56,
    bind_probability: 0.56,
    bind_shap: [
      { feature: "Quoted_Premium", value: 890, impact: 0.14 },
      { feature: "Coverage", value: 0, impact: -0.08 },
      { feature: "Agent_Type", value: 1, impact: 0.06 },
    ],
    bind_lime: { Quoted_Premium: 0.11, Coverage: -0.06, Agent_Type: 0.05 },
    bind_anchors: "IF risk_tier = MEDIUM AND Quoted_Premium < 1000 THEN moderate bind chance (precision: 71%)",
    bind_counterfactuals: [
      {
        original: { Quoted_Premium: 890, Coverage: "Basic" },
        changed: { Quoted_Premium: 750, Coverage: "Basic" },
        outcome: "Higher bind probability",
      },
    ],
    urgency_days: 18,
    premium_flag: null,
    adjusted_band: null,
    premium_reasoning: null,
    decision: "AGENT_FOLLOWUP",
    case_summary: "Medium-risk experienced driver with moderate conversion potential. Basic coverage suggests price-sensitive buyer. Agent follow-up recommended to explore coverage options.",
    confidence: 0.72,
  },
  {
    quote_num: "Q-20250305-0004",
    agent_type: "IA",
    region: "West",
    timestamp: "2025-03-05T09:25:33Z",
    re_quote: false,
    quoted_premium: 1580.0,
    coverage: "Balanced",
    sal_range: "75K-100K",
    vehicl_cost_range: "35K-50K",
    driver_age: 41,
    driving_exp: 20,
    prev_accidents: 0,
    prev_citations: 0,
    risk_tier: "LOW",
    risk_score: 0.11,
    risk_shap: [
      { feature: "Prev_Accidents", value: 0, impact: -0.35 },
      { feature: "Prev_Citations", value: 0, impact: -0.22 },
      { feature: "Driving_Exp", value: 20, impact: -0.18 },
    ],
    risk_lime: { Prev_Accidents: -0.31, Prev_Citations: -0.2, Driving_Exp: -0.16 },
    risk_anchors: "IF Prev_Accidents = 0 AND Prev_Citations = 0 THEN LOW risk (precision: 97%)",
    risk_counterfactuals: [
      {
        original: { Prev_Accidents: 0, Prev_Citations: 0 },
        changed: { Prev_Accidents: 3, Prev_Citations: 2 },
        outcome: "HIGH risk",
      },
    ],
    bind_score: 88,
    bind_probability: 0.88,
    bind_shap: [
      { feature: "risk_tier", value: 0, impact: 0.22 },
      { feature: "Sal_Range", value: 3, impact: 0.15 },
      { feature: "Quoted_Premium", value: 1580, impact: 0.11 },
    ],
    bind_lime: { risk_tier: 0.19, Sal_Range: 0.13, Quoted_Premium: 0.09 },
    bind_anchors: "IF risk_tier = LOW AND Sal_Range >= 75K THEN bind (precision: 92%)",
    bind_counterfactuals: [
      {
        original: { Quoted_Premium: 1580, Coverage: "Balanced" },
        changed: { Quoted_Premium: 2400, Coverage: "Balanced" },
        outcome: "No bind",
      },
    ],
    urgency_days: 21,
    premium_flag: "ACCEPTABLE",
    adjusted_band: "$1400-$1700",
    premium_reasoning: "Premium of $1,580 is well-positioned for a 75K-100K earner with Balanced coverage. No affordability concern detected.",
    decision: "AUTO_APPROVE",
    case_summary: "Clean driving record, strong income bracket, competitive premium. All signals green for automatic binding.",
    confidence: 0.94,
  },
  {
    quote_num: "Q-20250305-0005",
    agent_type: "EA",
    region: "Southeast",
    timestamp: "2025-03-05T09:28:50Z",
    re_quote: true,
    quoted_premium: 1820.0,
    coverage: "Enhanced",
    sal_range: "50K-75K",
    vehicl_cost_range: "25K-35K",
    driver_age: 28,
    driving_exp: 7,
    prev_accidents: 1,
    prev_citations: 2,
    risk_tier: "MEDIUM",
    risk_score: 0.55,
    risk_shap: [
      { feature: "Prev_Citations", value: 2, impact: 0.2 },
      { feature: "Prev_Accidents", value: 1, impact: 0.18 },
      { feature: "Driver_Age", value: 28, impact: -0.05 },
    ],
    risk_lime: { Prev_Citations: 0.17, Prev_Accidents: 0.15, Driver_Age: -0.04 },
    risk_anchors: "IF Prev_Citations >= 2 AND Prev_Accidents >= 1 THEN MEDIUM risk (precision: 79%)",
    risk_counterfactuals: [
      {
        original: { Prev_Accidents: 1, Prev_Citations: 2 },
        changed: { Prev_Accidents: 0, Prev_Citations: 0 },
        outcome: "LOW risk",
      },
    ],
    bind_score: 48,
    bind_probability: 0.48,
    bind_shap: [
      { feature: "Quoted_Premium", value: 1820, impact: -0.16 },
      { feature: "Re_Quote", value: 1, impact: 0.1 },
      { feature: "risk_tier", value: 1, impact: -0.08 },
    ],
    bind_lime: { Quoted_Premium: -0.14, Re_Quote: 0.08, risk_tier: -0.06 },
    bind_anchors: "IF Quoted_Premium > 1700 AND risk_tier = MEDIUM THEN uncertain (precision: 65%)",
    bind_counterfactuals: [
      {
        original: { Quoted_Premium: 1820, Coverage: "Enhanced" },
        changed: { Quoted_Premium: 1300, Coverage: "Balanced" },
        outcome: "Bind likely",
      },
    ],
    urgency_days: 5,
    premium_flag: null,
    adjusted_band: null,
    premium_reasoning: null,
    decision: "AGENT_FOLLOWUP",
    case_summary: "Medium risk re-quote with declining conversion signals. Premium may be straining affordability. Agent outreach recommended to discuss coverage downgrade options.",
    confidence: 0.68,
  },
  {
    quote_num: "Q-20250305-0006",
    agent_type: "IA",
    region: "Northeast",
    timestamp: "2025-03-05T09:32:15Z",
    re_quote: false,
    quoted_premium: 2450.0,
    coverage: "Enhanced",
    sal_range: "35K-50K",
    vehicl_cost_range: "50K+",
    driver_age: 19,
    driving_exp: 1,
    prev_accidents: 1,
    prev_citations: 4,
    risk_tier: "HIGH",
    risk_score: 0.93,
    risk_shap: [
      { feature: "Driver_Age", value: 19, impact: 0.38 },
      { feature: "Prev_Citations", value: 4, impact: 0.31 },
      { feature: "Driving_Exp", value: 1, impact: 0.25 },
    ],
    risk_lime: { Driver_Age: 0.35, Prev_Citations: 0.28, Driving_Exp: 0.22 },
    risk_anchors: "IF Driver_Age < 21 AND Prev_Citations >= 3 THEN HIGH risk (precision: 98%)",
    risk_counterfactuals: [
      {
        original: { Driver_Age: 19, Prev_Citations: 4 },
        changed: { Driver_Age: 30, Prev_Citations: 0 },
        outcome: "LOW risk",
      },
    ],
    bind_score: 31,
    bind_probability: 0.31,
    bind_shap: [
      { feature: "risk_tier", value: 2, impact: -0.28 },
      { feature: "Quoted_Premium", value: 2450, impact: -0.22 },
      { feature: "Driver_Age", value: 19, impact: -0.15 },
    ],
    bind_lime: { risk_tier: -0.25, Quoted_Premium: -0.2, Driver_Age: -0.13 },
    bind_anchors: "IF risk_tier = HIGH AND Quoted_Premium > 2000 THEN no bind (precision: 91%)",
    bind_counterfactuals: [
      {
        original: { Quoted_Premium: 2450, risk_tier: "HIGH" },
        changed: { Quoted_Premium: 1200, risk_tier: "MEDIUM" },
        outcome: "Bind possible",
      },
    ],
    urgency_days: 25,
    premium_flag: null,
    adjusted_band: null,
    premium_reasoning: null,
    decision: "ESCALATE_UNDERWRITER",
    case_summary: "Very young driver with significant citation history. High risk tier with low conversion probability. Premium significantly exceeds salary bracket capacity. Manual underwriter review required for risk acceptance decision.",
    confidence: 0.42,
  },
];

export const MOCK_STATS: StatsOverview = {
  total_quotes: 1247,
  bind_rate: 22.4,
  auto_approve_pct: 38.2,
  agent_followup_pct: 41.5,
  escalation_pct: 20.3,
  risk_distribution: [
    { tier: "LOW", count: 624 },
    { tier: "MEDIUM", count: 436 },
    { tier: "HIGH", count: 187 },
  ],
  decision_distribution: [
    { decision: "AUTO_APPROVE", count: 476 },
    { decision: "AGENT_FOLLOWUP", count: 518 },
    { decision: "ESCALATE_UNDERWRITER", count: 253 },
  ],
  bind_score_histogram: [
    { range: "0-10", count: 45 },
    { range: "11-20", count: 78 },
    { range: "21-30", count: 112 },
    { range: "31-40", count: 156 },
    { range: "41-50", count: 198 },
    { range: "51-60", count: 187 },
    { range: "61-70", count: 165 },
    { range: "71-80", count: 142 },
    { range: "81-90", count: 98 },
    { range: "91-100", count: 66 },
  ],
};

export const MOCK_REGIONAL: RegionalStats[] = [
  { region: "Northeast", total_quotes: 312, bind_rate: 24.1, ea_bind_rate: 28.3, ia_bind_rate: 19.8, avg_bind_score: 61.2, escalation_rate: 18.6, dynamic_threshold: 72 },
  { region: "Southeast", total_quotes: 287, bind_rate: 19.5, ea_bind_rate: 22.1, ia_bind_rate: 16.9, avg_bind_score: 53.8, escalation_rate: 24.7, dynamic_threshold: 68 },
  { region: "Midwest", total_quotes: 298, bind_rate: 23.8, ea_bind_rate: 27.5, ia_bind_rate: 20.1, avg_bind_score: 59.4, escalation_rate: 17.4, dynamic_threshold: 73 },
  { region: "West", total_quotes: 350, bind_rate: 21.7, ea_bind_rate: 25.2, ia_bind_rate: 18.3, avg_bind_score: 57.1, escalation_rate: 21.1, dynamic_threshold: 70 },
];
